CREATE SCHEMA EC5_SI1N;

USE EC5_SI1N;

CREATE TABLE IF NOT EXISTS CLIENTES (
  CPF_CLIENTE INT PRIMARY KEY,
  NOME_CLIENTE VARCHAR(45) NOT NULL,
  NUM_RUA_CLIENTE INT NOT NULL,
  BAIRRO_CLIENTE VARCHAR(45) NOT NULL,
  CIDADE_CLIENTE VARCHAR(45) NOT NULL,
  ESTADO_CLIENTE VARCHAR(45) NOT NULL,
  STATUS_FIDEL_CLIENTE VARCHAR(45) NOT NULL
);

CREATE TABLE IF NOT EXISTS FORNECEDORES (
  ID_FORN INT PRIMARY KEY,
  TEL_FORN INT NOT NULL,
  NUM_RUA_FORN INT NOT NULL,
  BAIRRO_FORN VARCHAR(45) NOT NULL,
  CIDADE_FORN VARCHAR(45) NOT NULL,
  ESTADO_FORN VARCHAR(45) NOT NULL
);

CREATE TABLE IF NOT EXISTS VENDAS (
  ID_VENDA INT PRIMARY KEY,
  CLIENTE_VENDA VARCHAR(45) NOT NULL,
  PROD_VENDA INT NOT NULL,
  FORM_PAG_VENDA VARCHAR(15) NOT NULL,
  DATA_VENDA DATE NOT NULL,
  CONSTRAINT FK_PRODUTOS FOREIGN KEY (PROD_VENDA) REFERENCES PRODUTOS(COD_PROD)
);

CREATE TABLE IF NOT EXISTS PRODUTOS (
  COD_PROD INT PRIMARY KEY,
  NOME_PROD VARCHAR(45) NOT NULL,
  CATEGO_PROD VARCHAR(45) NOT NULL,
  DISPO_ESTOQUE_PROD VARCHAR(50) NOT NULL,
  PRECO_PROD DECIMAL(10,2) NOT NULL,
  PROD_FORN INT NOT NULL,
  PROD_VENDA INT NOT NULL,
  CONSTRAINT FK_FORNECEDOR FOREIGN KEY (PROD_FORN) REFERENCES FORNECEDORES(ID_FORN),
  CONSTRAINT FK_VENDAS FOREIGN KEY (PROD_VENDA) REFERENCES VENDAS(ID_VENDA)
);

CREATE TABLE IF NOT EXISTS PAGAMENTOS (
  CONFIRM_PAG INT PRIMARY KEY,
  DATA_PAG DATE NOT NULL,
  HORA_PAG TIME,
  VALOR_PAG DECIMAL(10,2) NOT NULL
);

CREATE TABLE IF NOT EXISTS VENDAS_PRODUTOS (
  VDPR_VENDAS INT,
  VDPR_PRODUTOS INT,
  PRIMARY KEY(VDPR_VENDAS, VDPR_PRODUTOS),
  CONSTRAINT VDPR_FK_VENDAS FOREIGN KEY(VDPR_VENDAS) REFERENCES VENDAS(ID_VENDA),
  CONSTRAINT VDPR_FK_PRODUTOS FOREIGN KEY(VDPR_PRODUTOS) REFERENCES PRODUTOS(COD_PROD)
);

ALTER TABLE PAGAMENTOS 
  ADD STATUS_PAG VARCHAR(9) NOT NULL,
  DROP COLUMN HORA_PAG,
  MODIFY COLUMN STATUS_PAG ENUM('EM ESPERA', 'PENDENTE', 'CONCLUIDO'),
  CHANGE COLUMN CONFIRM_PAG ID_PAG INT PRIMARY KEY;

CREATE TABLE IF NOT EXISTS FORNECEDORES_PRODUTOS (
  FRPR_FORNECEDOR INT,
  FRPR_PRODUTOS INT,
  PRIMARY KEY(FRPR_FORNECEDOR, FRPR_PRODUTOS),
  CONSTRAINT FRPR_FK_FORNECEDORES FOREIGN KEY(FRPR_FORNECEDOR) REFERENCES FORNECEDORES(ID_FORN),
  CONSTRAINT FRPR_FK_PRODUTOS FOREIGN KEY(FRPR_PRODUTOS) REFERENCES PRODUTOS(COD_PROD)
);

ALTER TABLE PRODUTOS 
  ADD DESCRICAO_PROD TEXT NOT NULL,
  DROP COLUMN ESPEC_PROD,
  MODIFY COLUMN DISPO_ESTOQUE_PROD TEXT NOT NULL,
  CHANGE COLUMN PRECO_PROD PRECOUNI_PROD DECIMAL(10,2) NOT NULL;

ALTER TABLE CLIENTES 
  ADD EMAIL_CLIENTE VARCHAR(45) NOT NULL,
  DROP COLUMN DATA_NASC_CLIENTE,
  MODIFY COLUMN STATUS_FIDEL_CLIENTE VARCHAR(45) NOT NULL,
  CHANGE COLUMN NOME_CLIENTE NOMECOMP_CLIENTE VARCHAR(45) NOT NULL;

ALTER TABLE FORNECEDORES 
  ADD FORNEC_CONTATO TEXT NOT NULL,
  DROP COLUMN FORNEC_RUA,
  MODIFY COLUMN NUM_RUA_FORN INT NOT NULL,
  CHANGE COLUMN NUM_RUA_FORN NUMRUA_FORN INT NOT NULL;

ALTER TABLE VENDAS 
  ADD HORA_VENDA TIME NOT NULL,
  DROP COLUMN COD_VENDA,
  MODIFY COLUMN FORM_PAG_VENDA ENUM('DEBITO', 'CREDITO', 'CASH'),
  CHANGE COLUMN FORM_PAG_VENDA FORMPAG_VENDA ENUM('DEBITO', 'CREDITO', 'CASH');